/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz.neomtech.javafxmettle.utils;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * @author Dell
 */
public class Utils {

    public static String blurImage = "block.jpg";

    public static List<String> imageName = Arrays.asList(new String[]{
            "DJBS.jpg",
            "DJOS.jpg",
            "DBBB.jpg",
            "DCOS.jpg",
            "DBBM.jpg",
            "DBBS.jpg",
            "DBOB.jpg",
            "DBOM.jpg",
            "DBOS.jpg",
            "DBYB.jpg",
            "DBYM.jpg",
            "DBYS.jpg",
            "DCBB.jpg",
            "DCBM.jpg",
            "DCBS.jpg",
            "DCOB.jpg",
            "DCOM.jpg",
            "DCYB.jpg",
            "DCYM.jpg",
            "DCYS.jpg",
            "DJBB.jpg",
            "DJBM.jpg",
            "DJOB.jpg",
            "DJOM.jpg",
            "DJYB.jpg",
            "DJYM.jpg",
            "DJYS.jpg",
            "LBBB.jpg",
            "LBBM.jpg",
            "LBBS.jpg",
            "LBOB.jpg",
            "LBOM.jpg",
            "LBOS.jpg",
            "LBYB.jpg",
            "LBYM.jpg",
            "LBYS.jpg",
            "LCBB.jpg",
            "LCBM.jpg",
            "LCBS.jpg",
            "LCOB.jpg",
            "LCOM.jpg",
            "LCOS.jpg",
            "LCYB.jpg",
            "LCYM.jpg",
            "LCYS.jpg",
            "LJBB.jpg",
            "LJBM.jpg",
            "LJBS.jpg",
            "LJOB.jpg",
            "LJOM.jpg",
            "LJOS.jpg",
            "LJYB.jpg",
            "LJYM.jpg",
            "LJYS.jpg",
            "SBBB.jpg",
            "SBBM.jpg",
            "SBBS.jpg",
            "SBOB.jpg",
            "SBOM.jpg",
            "SBOS.jpg",
            "SBYB.jpg",
            "SBYM.jpg",
            "SBYS.jpg",
            "SCBB.jpg",
            "SCBM.jpg",
            "SCBS.jpg",
            "SCOB.jpg",
            "SCOM.jpg",
            "SCOS.jpg",
            "SCYB.jpg",
            "SCYM.jpg",
            "SCYS.jpg",
            "SJBB.jpg",
            "SJBM.jpg",
            "SJBS.jpg",
            "SJOB.jpg",
            "SJOM.jpg",
            "SJOS.jpg",
            "SJYB.jpg",
            "SJYM.jpg",
            "SJYS.jpg"
    });

//    public static List<String> imageName = Arrays.asList(new String[]{
//        "circle_L_blue_angle.png",
//        "circle_L_blue_hori.png",
//        "circle_L_blue_star.png",
//        "circle_L_green_angle.png",
//        "circle_L_green_hori.png",
//        "circle_L_green_star.png",
//        "circle_L_red_angle.png",
//        "circle_L_red_hori.png",
//        "circle_L_red_star.png",
//        "circle_m_blue_angle.png",
//        "circle_m_blue_hori.png",
//        "circle_m_blue_star.png",
//        "circle_m_green_angle.png",
//        "circle_m_green_hori.png",
//        "circle_m_green_star.png",
//        "circle_m_red_angle.png",
//        "circle_m_red_hori.png",
//        "circle_m_red_star.png",
//        "circle_s_blue_angle.png",
//        "circle_s_blue_hori.png",
//        "circle_s_blue_star.png",
//        "circle_s_green_angle.png",
//        "circle_s_green_hori.png",
//        "circle_s_green_star.png",
//        "circle_s_red_angle.png",
//        "circle_s_red_hori.png",
//        "circle_s_red_star.png",
//        "heart_L_blue_angle.png",
//        "heart_L_blue_hori.png",
//        "heart_L_blue_star.png",
//        "heart_L_green_angle.png",
//        "heart_L_green_hori.png",
//        "heart_L_green_star.png",
//        "heart_L_red_angle.png",
//        "heart_L_red_hori.png",
//        "heart_L_red_star.png",
//        "heart_m_blue_angle.png",
//        "heart_m_blue_hori.png",
//        "heart_m_blue_star.png",
//        "heart_m_green_angle.png",
//        "heart_m_green_hori.png",
//        "heart_m_green_star.png",
//        "heart_m_red_angle.png",
//        "heart_m_red_hori.png",
//        "heart_m_red_star.png",
//        "heart_s_blue_angle.png",
//        "heart_s_blue_hori.png",
//        "heart_s_blue_star.png",
//        "heart_s_green_angle.png",
//        "heart_s_green_hori.png",
//        "heart_s_green_star.png",
//        "heart_s_red_angle.png",
//        "heart_s_red_hori.png",
//        "heart_s_red_star.png",
//        "star_L_blue_angle.png",
//        "star_L_blue_hori.png",
//        "star_L_blue_star.png",
//        "star_L_green_angle.png",
//        "star_L_green_hori.png",
//        "star_L_green_star.png",
//        "star_L_red_angle.png",
//        "star_L_red_hori.png",
//        "star_L_red_star.png",
//        "star_m_blue_angle.png",
//        "star_m_blue_hori.png",
//        "star_m_blue_star.png",
//        "star_m_green_angle.png",
//        "star_m_green_hori.png",
//        "star_m_green_star.png",
//        "star_m_red_angle.png",
//        "star_m_red_hori.png",
//        "star_m_red_star.png",
//        "star_s_blue_angle.png",
//        "star_s_blue_hori.png",
//        "star_s_blue_star.png",
//        "star_s_green_angle.png",
//        "star_s_green_hori.png",
//        "star_s_green_star.png",
//        "star_s_red_angle.png",
//        "star_s_red_hori.png",
//        "star_s_red_star.png"
//    });

    public static void printImageName() {
        for (String item : imageName) {
            System.out.println(item);
        }
    }

}
